apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent-injector
  namespace: <your-namespace>
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: <your-namespace>
  labels:
    helm.sh/chart: vault-0.22.1
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
