apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: <your-namespace>
  labels:
    app.kubernetes.io/name: vault-ui
    app.kubernetes.io/instance: vault
spec:
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: server
      port: 8201
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: <your-namespace>
  labels:
    app.kubernetes.io/name: vault-ui
    app.kubernetes.io/instance: vault
spec:
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: server
      port: 8201
      targetPort: 8201
  type: LoadBalancer
